#!/bin/bash

rm nvc_main.x

CXX="nvc++"

LINKFLAG="-L/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/cuda/lib64 -L/usr/lib64/ -L/opt/local/lib/gcc11/"

NVCFLAG="-O3 -std=c++20 -target=gpu -Minline -fopenmp -cuda -stdpar=multicore"

$CXX $NVCFLAG $LINKFLAG -c vector_add.cpp && echo "Finish vector add"

$CXX $NVCFLAG $LINKFLAG vector_add.o -o nvc_main.x ; echo "Finished Linking"

rm *.o
